FROM alpine:3.17
RUN apk --no-cache add ca-certificates tzdata
COPY dist/traefik /usr/local/bin/traefik
COPY entrypoint.sh /
RUN chmod +x entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["traefik"]
